version: '3.8'
name: TMS

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 5000:5000
    volumes:
      - ./server:/app/server
      - /app/node_modules
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - server
