name: TMS

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 5000:5000
    volumes:
      - ./server:/app/server
      - /app/node_modules
    